project:
  type: website
  output-dir: docs

website:
  title: "Fendi Tsim"
  site-url: "https://fenditsim.github.io/"
  search: false
  favicon: img/logo.png
  navbar:
    background: "#FFFFFF"
    foreground: "#f01313"
    right:
      - text: "About Me"
        href: resume/index.qmd
      - text: "Research"
        menu:
        - text: "Publications"
          href: research/publications/index.qmd
        - text: "---"  # This creates a separator line
        - text: "Working Papers"
          href: research/working-papers/index.qmd
      - text: "Portfolio"
        href: portfolio/index.qmd
    
  page-footer: 
    left: "Â© 2025 Fendi Tsim" 
    right: "Built with [Quarto](https://quarto.org/)"

filters:
  - auto-dark

format:
  html:
    include-in-header: header.html
    theme: journal
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: true
    section-divs: true
    grid: 
      body-width: 1000px

metadata:
  google-site-verification: "tquQnBEuWnbNYy4Tu7J5gvL_QOJOK1ndTJQox0NA6GA"

editor: visual