project:
  type: website
  output-dir: docs

website:
  title: "Fendi Tsim"
  site-url: "https://fenditsim.github.io/"
  search: false
  favicon: img/logo.png
  navbar:
    background: "#FFFFFF"
    foreground: "#f01313"
    right:
      - text: "About Me"
        href: resume/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Portfolio"
        href: portfolio/index.qmd
    
  page-footer: 
    left: "Â© 2026 Fendi Tsim" 
    right: "Built with [Quarto](https://quarto.org/)"

filters:
  - auto-dark

format:
  html:
    include-in-header: header.html
    theme: journal
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: true
    section-divs: true
    grid: 
      body-width: 1000px

editor: visual